classes = {'Capacitor', 'CurrentSource', 'Inductor',...
    'Resistor', 'VoltageSource'};
net = importKerasLayers('data/minivggnet_components_weights32x32.hdf5', ...
    'classNames', classes);

options = trainingOptions('sgdm', ...
    'InitialLearnRate',0.001, ...
    'Verbose',false, ...
    'Plots','training-progress');

imds = imageDatastore('img/indivPrinted/');

